daysUntilStale: 1
daysUntilClose: 1
exemptLabels:
  - good first issue
staleLabel: old
markComment: >
  Any updates? Did @KTibow forget to follow up?
  No point in keeping something open with no status updates.
closeComment: false
